version: '3.8'
services:
  apache:
    image: apache-server:latest
    container_name: apache-with-php-rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: "/"
    restart: always
    networks:
      app-network:
        ipv4_address: 172.28.1.1
networks:
  app-network:
    ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16