version: '3.8'
services:
  apache:
    image: apache-server:latest
    container_name: apache-with-php-postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passwrod
    ports:
      - "5432:5432"
    networks:
      app-network:
        ipv4_address: 172.28.1.1
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network
networks:
  app-network:
    ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16