version: '3.8'
services:
  apache:
    image: apache-server:latest
    container_name: apache-with-php-radis
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - app-network
  redis:
    container_name: redis
    image: redis:7.0.9-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network: