version: '3.8'
services:
  apache:
    image: apache-server:latest
    container_name: apache-with-php-mongodb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    container_name: mongo
    image: mongo:5.0
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production
    networks:
      - app-network
  mongo-express:
    container_name: mongoexpress
    image: mongo-express:1.0.0-alpha.4
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always
    ports:
      - "8081:8081"
networks:
  app-network:
volumes:
  mongo_data: