version: '3.8'
services:
  apache:
    image: apache-server:latest
    container_name: apache-with-php-mysql
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
volumes:
  db_data: