version: '3.8'
services:
  web:
    container_name: nginx-with-php
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
  php:
    image: php:8-fpm
    container_name: php8
    volumes:
      - ./src:/var/www/html/
    ports:
      - 9000:9000